apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: device-micro-go
  name: device-micro-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-micro-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: device-micro-go
    spec:
      containers:
      - image: localhost:5000/device-micro-go
        name: device-micro-go
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: device-micro-go
  name: device-micro-go
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: device-micro-go
  type: NodePort
status:
  loadBalancer: {}

